# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_snpData <- function(file, sep, quote, rowNames, na_str, nrows) {
    .Call('qtcat_read_snpData', PACKAGE = 'qtcat', file, sep, quote, rowNames, na_str, nrows)
}

corDist <- function(x, y) {
    .Call('qtcat_corDist', PACKAGE = 'qtcat', x, y)
}

corDists <- function(x) {
    .Call('qtcat_corDists', PACKAGE = 'qtcat', x)
}

corPreIdenticals <- function(x, step) {
    .Call('qtcat_corPreIdenticals', PACKAGE = 'qtcat', x, step)
}

corIdenticals <- function(x, clustIdx) {
    .Call('qtcat_corIdenticals', PACKAGE = 'qtcat', x, clustIdx)
}

joinCorIdenticals <- function(n, preclust, ClustMedo) {
    .Call('qtcat_joinCorIdenticals', PACKAGE = 'qtcat', n, preclust, ClustMedo)
}

corClarans <- function(x, k, maxNeigbours) {
    .Call('qtcat_corClarans', PACKAGE = 'qtcat', x, k, maxNeigbours)
}

corMedoids <- function(x, clusters) {
    .Call('qtcat_corMedoids', PACKAGE = 'qtcat', x, clusters)
}

design <- function(x, inx1, inx2) {
    .Call('qtcat_design', PACKAGE = 'qtcat', x, inx1, inx2)
}

freqs2 <- function(x) {
    .Call('qtcat_freqs2', PACKAGE = 'qtcat', x)
}

freq1 <- function(x) {
    .Call('qtcat_freq1', PACKAGE = 'qtcat', x)
}

